apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-dev
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/sh
    - -c
    args:
    - minio server /data --console-address :9090
    ports:
    - containerPort: 9090
      protocol: TCP
    volumeMounts:
    - mountPath: /data
      name: localvolume
  nodeSelector:
    kubernetes.io/hostname: kubealpha.local
  volumes:
  - name: localvolume
    hostPath:
      path: /mnt/disk1/data
      type: DirectoryOrCreate
