apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-data
  namespace: word
spec:
  schedule: "13 0 * * *"  # Run at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: alpine:tag  # Use the image with your backup script
            command: ["/bin/sh", "-c"]
            args:
              - /home/samuel/word/word/script/back-up.sh
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          restartPolicy: OnFailure
