apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-wordpress
  namespace: word
spec:
  schedule: "51 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: wordpress:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                export TERM=vt100
                apt-get update && apt-get install -y tar mc
                mkdir -p /backup
                tar -czf /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz -C /var/www/html/ .
                mc cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz minio/wordpress/wordpress_backup_$(date +"%Y-%m-%d").tar.gz
                cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz minio/wordpress/wordpress_backup_$(date +"%Y-%m-%d").tar.gz
                mc alias set minio http://127.0.0.1:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api S3v4
                mc cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz minio/wordpress/wordpress_backup_$(date +"%Y-%m-%d").tar.gz
                cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz minio/wordpress/wordpress_backup_$(date +"%Y-%m-%d").tar.gz
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: wordpress-persistent-storage
            persistentVolumeClaim:
              claimName: wordpress-pvc
          - name: backup-volume
            emptyDir: {}
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
