apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-wordpress
  namespace: word
spec:
  schedule: "40 21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: wordpress:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                export TERM=xterm
                apt-get update && apt-get install -y tar mc
                mkdir -p /backup
                tar -czf /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz -C /var/www/html/ .
                mc cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz myminio/backup/
                rm /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          restartPolicy: OnFailure
          volumes:
          - name: wordpress-persistent-storage
            persistentVolumeClaim:
              claimName: wordpress-pvc
          - name: backup-volume
            emptyDir: {}
