apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-word-data
  namespace: word
spec:
  schedule: "35 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: alpine:tag
            command: ["/bin/sh", "-c"]
            args:
              - /home/samuel/word/word/script/back-up.sh
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          restartPolicy: OnFailure
