apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-word-data
  namespace: word
spec:
  schedule: "09 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: samuelrak/travel:minio3
            command: ["/bin/sh", "-c"]
            args:
            - /usr/local/bin/back-up.sh
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          restartPolicy: OnFailure
