apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-deploy
  namespace: word
spec:
  replicas: 3
  selector:
    matchLabels:
      app: word-deploy
      version: v1
  template:
    metadata:
      labels:
        app: word-deploy
        version: v1
    spec:
      containers:
      - image: wordpress:latest
        name: word-deploy
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/wp-config.php
          name: wp-config-volume
          subPath: wp-config.php
      volumes:
      - configMap:
          name: word-config
        name: wp-config-volume
      - name: word-secret-volume
        secret:
          secretName: word-secret
