apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-deploy
  namespace: word
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word-deploy
      version: v1
  template:
    metadata:
      labels:
        app: word-deploy
        version: v1
    spec:
      containers:
      - image: wordpress:latest
        name: word-deploy
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/wp-config.php
          name: wp-config-volume
          subPath: wp-config.php
        - mountPath: /var/www/html/wp-content/plugins/classic-editor
          name: plugins-volume
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: wp-config-volume
        configMap:
          name: word-config
      - name: plugins-volume
        emptyDir: {}
      - name: word-secret-volume
        secret:
          secretName: word-secret
