apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-deploy
  namespace: word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-deploy
      version: v1
  template:
    metadata:
      labels:
        app: word-deploy
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker01
      containers:
      - image: wordpress:latest
        name: word-deploy
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args: ["apache2ctl -D FOREGROUND"]
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/apachectl", "-k", "graceful-stop"]
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-files
        - mountPath: /var/log/apache2
          name: apache-logs
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
        - name: RESTORE_TRUE
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: RESTORE_TRUE
      volumes:
      - name: plugins-volume
        emptyDir: {}
      - name: word-secret-volume
        secret:
          secretName: word-secret
      - name: wordpress-files
        persistentVolumeClaim:
          claimName: wordpress-pvc
      - name: apache-logs
        emptyDir: {}
      initContainers:
      - name: restore
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -f /var/log/apache2/error.log > /var/log/apache2/error_copy.log
          exit_code=$?
          echo "Exit code: $exit_code"
          exit $exit_code
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-files
        - mountPath: /var/log/apache2
          name: apache-logs
