apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mysql
  namespace: word
spec:
  schedule: "9 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup-container
            image: ubuntu:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                mkdir /backup
                curl https://dl.min.io/client/mc/release/linux-amd64/mc \
                --create-dirs \
                -o $HOME/minio-binaries/mc
                chmod +x $HOME/minio-binaries/mc
                export PATH=$PATH:$HOME/minio-binaries/
                apt-get update && apt-get install -y mysql-client
                mysqldump -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /backup/mysql_backup_$(date +"%Y-%m-%d").sql
                mc alias set myminio http://minio-service:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
                mc cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz myminio/wordpress/
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          restartPolicy: OnFailure
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pvc
          - name: backup-volume
            emptyDir: {}
