apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_ROOT_PASSWORD
        image: mysql:latest
        name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-data
        emptyDir: {}
      - name: mysql-init-script
        configMap:
          name: mysql-init-script
#       - name: mysql-config1
#         mountPath: /etc/mysql/conf.d
#       - name: mysql-init-script
#         mountPath: /etc/mysql/init.sql
#         subPath: init.sql
#     - name: mysql-config1
#       configMap:
#         name: mysql-config1
#     - name: mysql-init-script
#       configMap:
#         name: mysql-init-script
#        resources:
#          limits:
#            cpu: 200m
#            memory: 400Mi
#          requests:
#            cpu: 100m
#            memory: 370Mi
