apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          resources:
           requests:
             memory: "370Mi"
             cpu: "100m"
           limits:
             memory: "400Mi"
             cpu: "200m"
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
