apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /myminio/mysql/mysql --console-address :9090
        volumeMounts:
        - mountPath: /myminio/mysql/mysql/
          name: minio-volume
        - mountPath: /restore
          name: minio-backup-volume
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
      initContainers:
      - name: restore
        image: quay.io/minio/minio:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ "$RESTORE_ENABLED" = "true" ]; then
              if [ -f "/myminio/mysql/mysql/mysql_backup_2024-05-10.sql/d5e6cdc4-bc5b-4794-a50b-c5c1e3d77a22/part.1" ]; then
                  echo "mysql backup found"
                  mkdir -p /restore
                  cp /myminio/mysql/mysql/mysql_backup_2024-05-10.sql/d5e6cdc4-bc5b-4794-a50b-c5c1e3d77a22/part.1 /restore
                  restore_status=$?
                  echo "restore completed with status $restore_status"
              else
                  echo "mysql backup not found. skipping restore."
              fi
          else
              echo "restore is not enabled."
          fi
        env:
        - name: RESTORE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: RESTORE_ENABLED
        volumeMounts:
        - mountPath: /myminio/mysql/mysql
          name: minio-volume
        - mountPath: /restore
          name: minio-backup-volume
      volumes:
      - name: minio-volume
        hostPath:
          path: /myminio/mysql/mysql
          type: DirectoryOrCreate
      - name: minio-backup-volume
        emptyDir: {}
      nodeSelector:
        kubernetes.io/hostname: samuel
