apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: word
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data/wordpress --console-address :9090
    volumeMounts:
    - mountPath: /data/wordpress
      name: minio-volume
  nodeSelector:
    kubernetes.io/hostname: samuel
  volumes:
  - name: minio-volume
    hostPath:
      path: /data/wordpress
      type: DirectoryOrCreate
