apiVersion: v1
kind: Service
metadata:
  name: mimio-service
  namespace: word
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
    nodePort: 30090
  selector:
    app: word-deploy
    version: v1
